// Generated by Wrangler on Thu Aug 15 2024 20:56:28 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	TWILIO_ACCOUNT_SID: string;
	TWILIO_AUTH_TOKEN: string;
	TWILIO_PHONE_NUMER: string;
	USER_PHONE_NUMER: string;
	AI: Ai;
}
